-- Autocmds are automatically loaded on the VeryLazy event
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `powervim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("powervim_wrap_spell")
